## Question 1:
<h5>Create a 2D NumPy array with dimensions 5x5, filled with integers from 1 to 25.</h5>
<h5>Use slicing to:</h5>
<h6>1. Extract and display the third row of the array.</h6>
<h6>2. Extract and display the second column of the array.</h6>y.

In [2]:
import numpy as np
b = np.arange(1, 26).reshape(5,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [4]:
b[2,:]

array([11, 12, 13, 14, 15])

In [4]:
b[:,1]

array([ 2,  7, 12, 17, 22])

## Question 2:
<h5>Create a 2D NumPy array with dimensions 3x4, filled with any integers of your
choice Access and print the element at the second row and third colun.</h5>.


In [9]:
a = np.arange(1, 13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a[1,2]

7

## Question 3:
<h5>Create two NumPy arrays of the same size with random integers. Calculate their
element-wise sum and then display elements from new arrays wherever the sum is
greater than 50.
</h5>

In [19]:
arr1 = np.random.randint(1,50, size=(4,4))
arr2 = np.random.randint(1,50, size=(4,4))

sum_array = arr1 + arr2
result_index = np.where(sum_array > 50)
result_val = sum_array[result_index]

In [20]:
print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nElement-wise sum:")
print(sum_array)
print("\nElements where sum is greater than 50:")
print(result_val)

Array 1:
[[ 2  8 38 28]
 [ 8 22 37  8]
 [ 1 26 41 31]
 [28  7  7 32]]

Array 2:
[[16  8 34  1]
 [37 23 47 30]
 [22 47 46  4]
 [15  1 48 18]]

Element-wise sum:
[[18 16 72 29]
 [45 45 84 38]
 [23 73 87 35]
 [43  8 55 50]]

Elements where sum is greater than 50:
[72 84 73 87 55]
